[build]
target = "avr-specs/avr-atmega2560.json"

[target.'cfg(target_arch = "avr")']
runner = "ravedude mega2560 -cb 57600"
rustflags = ["-Clink-arg=-Wl,--allow-multiple-definition"]

[unstable]
build-std = ["core"]
